version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "f1forecast-prediction"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bym8q47ql407"
s3_prefix = "f1forecast-prediction"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

