AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  prediction-engine

  Sample SAM Template for prediction-engine

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  PredictFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: predict/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        Predict:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /predict
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PredictApi:
    Description: "API Gateway endpoint URL for Prod stage for Predict function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/f1-forecast/"
  PredictFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt PredictFunction.Arn
  PredictFunctionIamRole:
    Description: "Implicit IAM Role created for Predict function"
    Value: !GetAtt PredictFunctionRole.Arn
