branch-defaults:
  master:
    environment: update
environment-defaults:
  update:
    branch: null
    repository: null
global:
  application_name: f1forecast-predictionengine
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-2::platform/Docker running on
    64bit Amazon Linux 2/3.0.0
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application


